"""Initial schema: every PostgreSQL entity of ТЗ section 5.1.

Hand-edited after autogenerate:
- `usage_log` monthly range partitions + DEFAULT partition (5.1);
- append-only trigger on `audit_log` (FR-AB-01, NFR-S-11).

Revision ID: 0001
Revises:
Create Date: 2026-10-08 15:21:17.419211+00:00
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import date

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from payintel.core.partitions import months_from, partition_ddl

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.String(length=128), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("row_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
        sa.UniqueConstraint("row_hash", name=op.f("uq_audit_log_row_hash")),
    )
    op.create_index("ix_audit_log_object", "audit_log", ["object_type", "object_id"], unique=False)
    op.create_index("ix_audit_log_ts", "audit_log", ["ts"], unique=False)
    op.create_table(
        "detection_rule",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rule_id", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum(
                "provider",
                "payment_method",
                "platform",
                "tech",
                name="rule_target_type",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column(
            "signal_type",
            sa.Enum(
                "script_src",
                "network_host",
                "iframe_src",
                "js_global",
                "html_pattern",
                "form_action",
                "checkout_label",
                "platform_plugin",
                "header",
                "cookie",
                "favicon",
                name="signal_type",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("pattern", sa.Text(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column(
            "page_scope",
            sa.Enum(
                "any",
                "homepage",
                "product",
                "cart",
                "checkout",
                name="page_scope",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "needs_verification", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("source_file", sa.String(length=256), nullable=False),
        sa.Column(
            "loaded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detection_rule")),
        sa.UniqueConstraint("rule_id", "version", name="uq_detection_rule_rule_id_version"),
    )
    op.create_index(
        "ix_detection_rule_target", "detection_rule", ["target_type", "target_id"], unique=False
    )
    op.create_table(
        "domain",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("etld1", sa.String(length=253), nullable=False),
        sa.Column("tld", sa.String(length=63), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "candidate",
                "ecommerce",
                "not_ecommerce",
                "parked",
                "no_dns",
                "unreachable",
                "blocked",
                "optout",
                name="domain_status",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            server_default="candidate",
            nullable=False,
        ),
        sa.Column("optout", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domain")),
        sa.UniqueConstraint("etld1", name=op.f("uq_domain_etld1")),
    )
    op.create_index(op.f("ix_domain_status"), "domain", ["status"], unique=False)
    op.create_index(op.f("ix_domain_tld"), "domain", ["tld"], unique=False)
    op.create_table(
        "feature_flag",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("changed_by", sa.String(length=128), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_feature_flag")),
    )
    op.create_table(
        "optout_request",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "dns_txt",
                "well_known",
                name="optout_method",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("contact", sa.String(length=254), nullable=True),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_optout_request")),
        sa.UniqueConstraint("token", name=op.f("uq_optout_request_token")),
    )
    op.create_index(op.f("ix_optout_request_domain"), "optout_request", ["domain"], unique=False)
    op.create_table(
        "organization",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("legal_name", sa.String(length=256), nullable=False),
        sa.Column("reg_number", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "applied",
                "kyc_in_progress",
                "approved",
                "rejected",
                "active",
                "suspended",
                "terminated",
                name="org_status",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            server_default="applied",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization")),
    )
    op.create_index(op.f("ix_organization_status"), "organization", ["status"], unique=False)
    op.create_table(
        "platform",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "acquired",
                "closed",
                "deprecated",
                name="reference_status",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["platform.id"],
            name=op.f("fk_platform_parent_id_platform"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform")),
    )
    op.create_table(
        "provider",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "aliases",
            postgresql.ARRAY(sa.String(length=128)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum(
                "gateway",
                "wallet",
                "bnpl",
                "local_method_provider",
                "orchestrator",
                "fraud_tool",
                "3ds_sdk",
                name="provider_role",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("owner_company", sa.String(length=256), nullable=True),
        sa.Column("parent_provider_id", sa.String(length=64), nullable=True),
        sa.Column(
            "countries",
            postgresql.ARRAY(sa.String(length=2)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("website", sa.String(length=256), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "acquired",
                "closed",
                "deprecated",
                name="reference_status",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_provider_id"],
            ["provider.id"],
            name=op.f("fk_provider_parent_provider_id_provider"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider")),
    )
    op.create_table(
        "usage_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("api_key_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("endpoint", sa.String(length=128), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("records", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", "ts", name=op.f("pk_usage_log")),
        postgresql_partition_by="RANGE (ts)",
    )
    op.create_index("ix_usage_log_org_id_ts", "usage_log", ["org_id", "ts"], unique=False)
    # Monthly partitions for a fixed initial window (deterministic) + DEFAULT.
    for year, month in months_from(date(2026, 10, 1), 15):
        op.execute(partition_ddl(year, month))
    op.execute("CREATE TABLE IF NOT EXISTS usage_log_default PARTITION OF usage_log DEFAULT")
    op.create_table(
        "user_account",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False, comment="argon2id (NFR-S-02)"),
        sa.Column(
            "totp_secret_encrypted",
            sa.Text(),
            nullable=True,
            comment="AES-GCM, key from env (NFR-S-03)",
        ),
        sa.Column("is_staff", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("failed_logins", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_account")),
        sa.UniqueConstraint("email", name=op.f("uq_user_account_email")),
    )
    op.create_table(
        "vertical",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column(
            "keywords",
            postgresql.ARRAY(sa.String(length=64)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "acquired",
                "closed",
                "deprecated",
                name="reference_status",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["vertical.id"],
            name=op.f("fk_vertical_parent_id_vertical"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vertical")),
    )
    op.create_table(
        "api_key",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column(
            "scopes",
            postgresql.ARRAY(sa.String(length=64)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "allowed_ips",
            postgresql.ARRAY(sa.String(length=64)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user_account.id"],
            name=op.f("fk_api_key_created_by_user_account"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
            name=op.f("fk_api_key_org_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_key")),
        sa.UniqueConstraint("hash", name=op.f("uq_api_key_hash")),
    )
    op.create_index(op.f("ix_api_key_org_id"), "api_key", ["org_id"], unique=False)
    op.create_index(op.f("ix_api_key_prefix"), "api_key", ["prefix"], unique=False)
    op.create_table(
        "contract",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.String(length=64), nullable=False),
        sa.Column(
            "product",
            sa.Enum(
                "c_report",
                "c_data",
                "c2",
                name="product",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column(
            "allowed_purposes",
            postgresql.ARRAY(sa.String(length=64)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("file_key", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
            name=op.f("fk_contract_org_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract")),
        sa.UniqueConstraint("number", name="uq_contract_number"),
    )
    op.create_table(
        "domain_source",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("domain_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "tranco",
                "commoncrawl",
                "ct",
                "crawl_link",
                "manual",
                "czds",
                name="domain_source_kind",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("batch_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domain.id"],
            name=op.f("fk_domain_source_domain_id_domain"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domain_source")),
        sa.UniqueConstraint("domain_id", "source", name="uq_domain_source_domain_id_source"),
    )
    op.create_index(
        "ix_domain_source_source_last_seen", "domain_source", ["source", "last_seen"], unique=False
    )
    op.create_table(
        "export_job",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "full_snapshot",
                "increment",
                "market_aggregates",
                name="export_type",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "format",
            sa.Enum(
                "parquet",
                "csv",
                name="export_format",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "awaiting_approval",
                "running",
                "done",
                "failed",
                "expired",
                name="export_status",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("rows", sa.Integer(), nullable=True),
        sa.Column("file_key", sa.String(length=512), nullable=True),
        sa.Column("watermark_id", sa.UUID(), nullable=False),
        sa.Column(
            "canary_ids",
            postgresql.ARRAY(sa.BigInteger()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("requested_by", sa.UUID(), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("download_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
            name=op.f("fk_export_job_org_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_export_job")),
    )
    op.create_index(op.f("ix_export_job_org_id"), "export_job", ["org_id"], unique=False)
    op.create_table(
        "host",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("domain_id", sa.BigInteger(), nullable=False),
        sa.Column("hostname", sa.String(length=253), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("last_resolved_ips", postgresql.ARRAY(postgresql.INET()), nullable=True),
        sa.Column("asn", sa.BigInteger(), nullable=True),
        sa.Column("hosting_country", sa.String(length=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"], ["domain.id"], name=op.f("fk_host_domain_id_domain"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_host")),
        sa.UniqueConstraint("hostname", name="uq_host_hostname"),
    )
    op.create_index(op.f("ix_host_domain_id"), "host", ["domain_id"], unique=False)
    op.create_table(
        "kyc_record",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("website", sa.String(length=256), nullable=True),
        sa.Column(
            "beneficiaries",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("contact_name", sa.String(length=256), nullable=True),
        sa.Column("contact_title", sa.String(length=128), nullable=True),
        sa.Column("purpose", sa.String(length=64), nullable=True),
        sa.Column(
            "documents",
            postgresql.ARRAY(sa.String(length=512)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("sanctions_result", sa.String(length=32), nullable=True),
        sa.Column("sanctions_source", sa.String(length=128), nullable=True),
        sa.Column("sanctions_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("video_call_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "decision",
            sa.Enum(
                "approved",
                "rejected",
                name="kyc_decision",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=True,
        ),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_comment", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
            name=op.f("fk_kyc_record_org_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kyc_record")),
        sa.UniqueConstraint("org_id", name=op.f("uq_kyc_record_org_id")),
    )
    op.create_table(
        "membership",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=True, comment="NULL for staff roles"),
        sa.Column(
            "role",
            sa.Enum(
                "org_viewer",
                "org_analyst",
                "org_admin",
                "api_client",
                "staff_support",
                "staff_analyst",
                "staff_compliance",
                "staff_admin",
                name="role",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
            name=op.f("fk_membership_org_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_membership_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership")),
        sa.UniqueConstraint("user_id", "org_id", name="uq_membership_user_id_org_id"),
    )
    op.create_table(
        "payment_method",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "card",
                "wallet",
                "bnpl",
                "bank_redirect",
                "bank_transfer",
                "direct_debit",
                "cash_voucher",
                "real_time_payment",
                "crypto",
                "cod",
                "other",
                name="payment_method_type",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("scheme_or_brand", sa.String(length=128), nullable=True),
        sa.Column(
            "regions",
            postgresql.ARRAY(sa.String(length=16)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("default_provider_id", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "acquired",
                "closed",
                "deprecated",
                name="reference_status",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["default_provider_id"],
            ["provider.id"],
            name=op.f("fk_payment_method_default_provider_id_provider"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_method")),
    )
    op.create_table(
        "watchlist",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
            name=op.f("fk_watchlist_org_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist")),
        sa.UniqueConstraint("org_id", "name", name="uq_watchlist_org_id_name"),
    )
    op.create_table(
        "webhook",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("secret_encrypted", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
            name=op.f("fk_webhook_org_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook")),
    )
    op.create_table(
        "alert_rule",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("watchlist_id", sa.BigInteger(), nullable=True),
        sa.Column("event_types", postgresql.ARRAY(sa.String(length=48)), nullable=False),
        sa.Column("provider_id", sa.String(length=64), nullable=True),
        sa.Column("method_id", sa.String(length=64), nullable=True),
        sa.Column("min_confidence", sa.String(length=8), server_default="medium", nullable=False),
        sa.Column(
            "channel",
            sa.String(length=16),
            nullable=False,
            comment="telegram | webhook (FR-AL-04; no e-mail, AS-19)",
        ),
        sa.Column("webhook_id", sa.BigInteger(), nullable=True),
        sa.Column("telegram_chat_id", sa.String(length=64), nullable=True),
        sa.Column("digest", sa.String(length=16), server_default="daily", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
            name=op.f("fk_alert_rule_org_id_organization"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlist.id"],
            name=op.f("fk_alert_rule_watchlist_id_watchlist"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["webhook.id"],
            name=op.f("fk_alert_rule_webhook_id_webhook"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_rule")),
    )
    op.create_table(
        "canary",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("export_job_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_hit_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["export_job_id"],
            ["export_job.id"],
            name=op.f("fk_canary_export_job_id_export_job"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
            name=op.f("fk_canary_org_id_organization"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canary")),
        sa.UniqueConstraint("domain", name=op.f("uq_canary_domain")),
    )
    op.create_index(op.f("ix_canary_org_id"), "canary", ["org_id"], unique=False)
    op.create_table(
        "entitlement",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("contract_id", sa.UUID(), nullable=False),
        sa.Column(
            "countries",
            postgresql.ARRAY(sa.String(length=2)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "platforms",
            postgresql.ARRAY(sa.String(length=64)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "field_profile",
            sa.Enum(
                "c1_basic",
                "c1_full",
                "c2_risk",
                name="field_profile",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("api_rps", sa.Integer(), nullable=False),
        sa.Column("daily_records", sa.Integer(), nullable=False),
        sa.Column("monthly_records", sa.Integer(), nullable=False),
        sa.Column("export_max_rows", sa.Integer(), nullable=False),
        sa.Column(
            "export_schedule", sa.String(length=32), server_default="monthly", nullable=False
        ),
        sa.Column("watchlist_limit", sa.Integer(), nullable=False),
        sa.Column(
            "allowed_ips",
            postgresql.ARRAY(sa.String(length=64)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contract.id"],
            name=op.f("fk_entitlement_contract_id_contract"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entitlement")),
        sa.UniqueConstraint("contract_id", name=op.f("uq_entitlement_contract_id")),
    )
    op.create_table(
        "gold_label",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("host_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "provider",
                "payment_method",
                "platform",
                "country",
                name="gold_entity_type",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("present", sa.Boolean(), nullable=False),
        sa.Column("labeled_by", sa.String(length=128), nullable=False),
        sa.Column("labeled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["host_id"], ["host.id"], name=op.f("fk_gold_label_host_id_host"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gold_label")),
        sa.UniqueConstraint(
            "host_id", "entity_type", "entity_id", name="uq_gold_label_host_entity"
        ),
    )
    op.create_index(op.f("ix_gold_label_host_id"), "gold_label", ["host_id"], unique=False)
    op.create_table(
        "scan_plan",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("host_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "scan_type",
            sa.Enum(
                "light",
                "checkout",
                name="scan_type",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("next_scan_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fail_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["host_id"], ["host.id"], name=op.f("fk_scan_plan_host_id_host"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_plan")),
        sa.UniqueConstraint("host_id", "scan_type", name="uq_scan_plan_host_id_scan_type"),
    )
    op.create_index(
        "ix_scan_plan_queue", "scan_plan", ["scan_type", "next_scan_at", "priority"], unique=False
    )
    op.create_table(
        "scan_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("host_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "scan_type",
            sa.Enum(
                "light",
                "checkout",
                name="scan_type",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "reached_payment_step",
                "reached_checkout",
                "reached_cart",
                "login_required",
                "registration_pending_verification",
                "no_product_found",
                "add_to_cart_failed",
                "blocked",
                "timeout",
                "error",
                "ok",
                "http_error",
                "robots_disallowed",
                "running",
                name="scan_status",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "coverage",
            sa.Enum(
                "homepage",
                "product",
                "cart",
                "checkout",
                "payment_step",
                name="coverage",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=True,
        ),
        sa.Column("stop_step", sa.String(length=32), nullable=True),
        sa.Column("stop_reason", sa.String(length=64), nullable=True),
        sa.Column("checkout_country", sa.String(length=2), nullable=True),
        sa.Column("used_account", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("worker_id", sa.String(length=128), nullable=False),
        sa.Column("ruleset_version", sa.String(length=64), nullable=False),
        sa.Column("artifact_prefix", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["host_id"], ["host.id"], name=op.f("fk_scan_run_host_id_host"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_run")),
    )
    op.create_index(
        "ix_scan_run_host_id_started_at", "scan_run", ["host_id", "started_at"], unique=False
    )
    op.create_index(
        "ix_scan_run_status_started_at", "scan_run", ["status", "started_at"], unique=False
    )
    op.create_table(
        "store_payment_method",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("host_id", sa.BigInteger(), nullable=False),
        sa.Column("method_id", sa.String(length=64), nullable=False),
        sa.Column("provider_id", sa.String(length=64), nullable=True),
        sa.Column(
            "confidence",
            sa.Enum(
                "high",
                "medium",
                "low",
                name="confidence_level",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("first_seen", sa.Date(), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=False),
        sa.Column("confirmations", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("misses", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["host.id"],
            name=op.f("fk_store_payment_method_host_id_host"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["method_id"],
            ["payment_method.id"],
            name=op.f("fk_store_payment_method_method_id_payment_method"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["provider.id"],
            name=op.f("fk_store_payment_method_provider_id_provider"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_payment_method")),
        sa.UniqueConstraint(
            "host_id", "method_id", name="uq_store_payment_method_host_id_method_id"
        ),
    )
    op.create_index(
        "ix_store_payment_method_method_id", "store_payment_method", ["method_id"], unique=False
    )
    op.create_table(
        "store_profile",
        sa.Column("host_id", sa.BigInteger(), nullable=False),
        sa.Column("platform_id", sa.String(length=64), nullable=True),
        sa.Column(
            "platform_confidence",
            sa.Enum(
                "high",
                "medium",
                "low",
                name="platform_confidence",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=True,
        ),
        sa.Column(
            "platform_version",
            sa.String(length=64),
            nullable=True,
            comment="Internal only (AS-23); never in C1 schemas",
        ),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column(
            "country_confidence",
            sa.Enum(
                "high",
                "medium",
                "low",
                name="country_confidence",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=True,
        ),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("vertical_id", sa.String(length=64), nullable=True),
        sa.Column(
            "vertical_confidence",
            sa.Enum(
                "high",
                "medium",
                "low",
                name="vertical_confidence",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=True,
        ),
        sa.Column(
            "checkout_status",
            sa.Enum(
                "reached_payment_step",
                "reached_checkout",
                "reached_cart",
                "login_required",
                "registration_pending_verification",
                "no_product_found",
                "add_to_cart_failed",
                "blocked",
                "timeout",
                "error",
                "ok",
                "http_error",
                "robots_disallowed",
                "running",
                name="scan_status",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=True,
        ),
        sa.Column(
            "coverage",
            sa.Enum(
                "homepage",
                "product",
                "cart",
                "checkout",
                "payment_step",
                name="coverage",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=True,
        ),
        sa.Column("checkout_country", sa.String(length=2), nullable=True),
        sa.Column("acquirer_hidden", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("last_light_scan_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_checkout_scan_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("traffic_rank", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["host_id"], ["host.id"], name=op.f("fk_store_profile_host_id_host"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platform.id"],
            name=op.f("fk_store_profile_platform_id_platform"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vertical_id"],
            ["vertical.id"],
            name=op.f("fk_store_profile_vertical_id_vertical"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("host_id", name=op.f("pk_store_profile")),
    )
    op.create_index(
        "ix_store_profile_country_platform",
        "store_profile",
        ["country", "platform_id"],
        unique=False,
    )
    op.create_index(
        "ix_store_profile_traffic_rank", "store_profile", ["traffic_rank"], unique=False
    )
    op.create_table(
        "store_provider",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("host_id", sa.BigInteger(), nullable=False),
        sa.Column("provider_id", sa.String(length=64), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "gateway",
                "wallet",
                "bnpl",
                "local_method_provider",
                "orchestrator",
                "fraud_tool",
                "3ds_sdk",
                name="provider_role",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Enum(
                "high",
                "medium",
                "low",
                name="confidence_level",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("active_on_checkout", sa.Boolean(), nullable=False),
        sa.Column("first_seen", sa.Date(), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=False),
        sa.Column("confirmations", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "misses",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Consecutive successful scans without the entity (FR-HI-04)",
        ),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["host.id"],
            name=op.f("fk_store_provider_host_id_host"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["provider.id"],
            name=op.f("fk_store_provider_provider_id_provider"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_provider")),
        sa.UniqueConstraint("host_id", "provider_id", name="uq_store_provider_host_id_provider_id"),
    )
    op.create_index(
        "ix_store_provider_provider_id", "store_provider", ["provider_id"], unique=False
    )
    op.create_table(
        "watchlist_item",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("watchlist_id", sa.BigInteger(), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlist.id"],
            name=op.f("fk_watchlist_item_watchlist_id_watchlist"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist_item")),
        sa.UniqueConstraint("watchlist_id", "domain", name="uq_watchlist_item_watchlist_id_domain"),
    )
    op.create_index(op.f("ix_watchlist_item_domain"), "watchlist_item", ["domain"], unique=False)
    op.create_table(
        "change_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("host_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "provider_added",
                "provider_removed",
                "method_added",
                "method_removed",
                "platform_changed",
                "checkout_host_added",
                "checkout_host_removed",
                "store_offline",
                "store_online",
                name="change_event_type",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=253), nullable=True),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scan_run_id", sa.UUID(), nullable=False),
        sa.Column("suppressed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_id"], ["host.id"], name=op.f("fk_change_event_host_id_host"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["scan_run_id"],
            ["scan_run.id"],
            name=op.f("fk_change_event_scan_run_id_scan_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_event")),
    )
    op.create_index(
        "ix_change_event_host_id_detected_at",
        "change_event",
        ["host_id", "detected_at"],
        unique=False,
    )
    op.create_index(
        "ix_change_event_type_detected_at",
        "change_event",
        ["event_type", "detected_at"],
        unique=False,
    )
    op.create_table(
        "store_account",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("host_id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_encrypted", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "pending_verification",
                "failed",
                "deleted",
                name="store_account_status",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_scan_run_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_scan_run_id"],
            ["scan_run.id"],
            name=op.f("fk_store_account_created_scan_run_id_scan_run"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["host_id"], ["host.id"], name=op.f("fk_store_account_host_id_host"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_store_account")),
        sa.UniqueConstraint("host_id", name=op.f("uq_store_account_host_id")),
    )
    op.create_table(
        "delivery",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("alert_rule_id", sa.BigInteger(), nullable=False),
        sa.Column("change_event_id", sa.BigInteger(), nullable=True),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "delivered",
                "failed",
                name="delivery_status",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["alert_rule_id"],
            ["alert_rule.id"],
            name=op.f("fk_delivery_alert_rule_id_alert_rule"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["change_event_id"],
            ["change_event.id"],
            name=op.f("fk_delivery_change_event_id_change_event"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery")),
    )
    # audit_log is append-only (FR-AB-01): reject UPDATE/DELETE at the database level.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_log_block_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only (FR-AB-01)';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER trg_audit_log_append_only BEFORE UPDATE OR DELETE ON audit_log "
        "FOR EACH ROW EXECUTE FUNCTION audit_log_block_mutation()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_audit_log_append_only ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_block_mutation()")
    op.drop_table("delivery")
    op.drop_table("store_account")
    op.drop_index("ix_change_event_type_detected_at", table_name="change_event")
    op.drop_index("ix_change_event_host_id_detected_at", table_name="change_event")
    op.drop_table("change_event")
    op.drop_index(op.f("ix_watchlist_item_domain"), table_name="watchlist_item")
    op.drop_table("watchlist_item")
    op.drop_index("ix_store_provider_provider_id", table_name="store_provider")
    op.drop_table("store_provider")
    op.drop_index("ix_store_profile_traffic_rank", table_name="store_profile")
    op.drop_index("ix_store_profile_country_platform", table_name="store_profile")
    op.drop_table("store_profile")
    op.drop_index("ix_store_payment_method_method_id", table_name="store_payment_method")
    op.drop_table("store_payment_method")
    op.drop_index("ix_scan_run_status_started_at", table_name="scan_run")
    op.drop_index("ix_scan_run_host_id_started_at", table_name="scan_run")
    op.drop_table("scan_run")
    op.drop_index("ix_scan_plan_queue", table_name="scan_plan")
    op.drop_table("scan_plan")
    op.drop_index(op.f("ix_gold_label_host_id"), table_name="gold_label")
    op.drop_table("gold_label")
    op.drop_table("entitlement")
    op.drop_index(op.f("ix_canary_org_id"), table_name="canary")
    op.drop_table("canary")
    op.drop_table("alert_rule")
    op.drop_table("webhook")
    op.drop_table("watchlist")
    op.drop_table("payment_method")
    op.drop_table("membership")
    op.drop_table("kyc_record")
    op.drop_index(op.f("ix_host_domain_id"), table_name="host")
    op.drop_table("host")
    op.drop_index(op.f("ix_export_job_org_id"), table_name="export_job")
    op.drop_table("export_job")
    op.drop_index("ix_domain_source_source_last_seen", table_name="domain_source")
    op.drop_table("domain_source")
    op.drop_table("contract")
    op.drop_index(op.f("ix_api_key_prefix"), table_name="api_key")
    op.drop_index(op.f("ix_api_key_org_id"), table_name="api_key")
    op.drop_table("api_key")
    op.drop_table("vertical")
    op.drop_table("user_account")
    op.drop_index("ix_usage_log_org_id_ts", table_name="usage_log")
    op.drop_table("usage_log")
    op.drop_table("provider")
    op.drop_table("platform")
    op.drop_index(op.f("ix_organization_status"), table_name="organization")
    op.drop_table("organization")
    op.drop_index(op.f("ix_optout_request_domain"), table_name="optout_request")
    op.drop_table("optout_request")
    op.drop_table("feature_flag")
    op.drop_index(op.f("ix_domain_tld"), table_name="domain")
    op.drop_index(op.f("ix_domain_status"), table_name="domain")
    op.drop_table("domain")
    op.drop_index("ix_detection_rule_target", table_name="detection_rule")
    op.drop_table("detection_rule")
    op.drop_index("ix_audit_log_ts", table_name="audit_log")
    op.drop_index("ix_audit_log_object", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
