"""Stage 1: import batches (FR-DS-03), DNS fields on host (FR-DS-06), JS asset dedup (FR-LS-03),
Tranco rank and classifier score on domain (FR-SC-02, FR-DS-08).

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 17:12:52.944416+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batch",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "tranco",
                "commoncrawl",
                "ct",
                "crawl_link",
                "manual",
                "czds",
                name="import_batch_source",
                native_enum=False,
                create_constraint=True,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("origin", sa.Text(), nullable=False, comment="file name, URL or feed identifier"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_seen", sa.Integer(), nullable=False),
        sa.Column("records_invalid", sa.Integer(), nullable=False),
        sa.Column("domains_new", sa.Integer(), nullable=False),
        sa.Column("domains_updated", sa.Integer(), nullable=False),
        sa.Column("hosts_new", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batch")),
    )
    op.create_index(op.f("ix_import_batch_source"), "import_batch", ["source"], unique=False)
    op.create_table(
        "js_asset",
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("s3_key", sa.String(length=256), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("sha256", name=op.f("pk_js_asset")),
    )
    op.create_table(
        "host_js_asset",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("host_id", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("src_url", sa.String(length=2048), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_id"], ["host.id"], name=op.f("fk_host_js_asset_host_id_host"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["sha256"],
            ["js_asset.sha256"],
            name=op.f("fk_host_js_asset_sha256_js_asset"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_host_js_asset")),
        sa.UniqueConstraint("host_id", "sha256", name="uq_host_js_asset_host_id_sha256"),
    )
    op.create_index(op.f("ix_host_js_asset_sha256"), "host_js_asset", ["sha256"], unique=False)
    op.add_column(
        "domain",
        sa.Column(
            "status_reason",
            sa.String(length=64),
            nullable=True,
            comment="e.g. parking signature id or classifier verdict",
        ),
    )
    op.add_column(
        "domain", sa.Column("status_changed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "domain",
        sa.Column(
            "traffic_rank", sa.Integer(), nullable=True, comment="Tranco rank, feeds FR-SC-02"
        ),
    )
    op.add_column(
        "domain",
        sa.Column(
            "ecommerce_confidence",
            sa.Float(),
            nullable=True,
            comment="FR-DS-08 classifier score 0..1",
        ),
    )
    op.create_index(op.f("ix_domain_traffic_rank"), "domain", ["traffic_rank"], unique=False)
    op.add_column("host", sa.Column("cname", sa.String(length=253), nullable=True))
    op.add_column("host", sa.Column("mx", postgresql.ARRAY(sa.String(length=253)), nullable=True))
    op.add_column("host", sa.Column("ns", postgresql.ARRAY(sa.String(length=253)), nullable=True))
    op.add_column(
        "host",
        sa.Column(
            "dns_status",
            sa.String(length=16),
            nullable=True,
            comment="ok | no_dns | error (FR-DS-06)",
        ),
    )
    op.add_column("host", sa.Column("dns_checked_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_host_dns_checked_at"), "host", ["dns_checked_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_host_dns_checked_at"), table_name="host")
    op.drop_column("host", "dns_checked_at")
    op.drop_column("host", "dns_status")
    op.drop_column("host", "ns")
    op.drop_column("host", "mx")
    op.drop_column("host", "cname")
    op.drop_index(op.f("ix_domain_traffic_rank"), table_name="domain")
    op.drop_column("domain", "ecommerce_confidence")
    op.drop_column("domain", "traffic_rank")
    op.drop_column("domain", "status_changed_at")
    op.drop_column("domain", "status_reason")
    op.drop_index(op.f("ix_host_js_asset_sha256"), table_name="host_js_asset")
    op.drop_table("host_js_asset")
    op.drop_table("js_asset")
    op.drop_index(op.f("ix_import_batch_source"), table_name="import_batch")
    op.drop_table("import_batch")
    # ### end Alembic commands ###
